# Generated by Django 6.0.4 on 2026-04-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.IntegerField()),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=20)),
                ('problema', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('p', 'Pendente'), ('a', 'Andamento'), ('f', 'Finalizado')], default='p', max_length=1)),
                ('notas', models.CharField(max_length=250)),
            ],
        ),
    ]
